Dev1
fluckmic/thymio-ar-demo pull request #1
Opened 2017-07-27 13:57 UTC by fluckmic

2017-08-08 14:59 UTC, fluckmic commented
I hope you get a notification if i mention you here, @stephanemagnenat.

2017-08-09 07:55 UTC, stephanemagnenat commented
A general comment: as the this library originally is indented by tabs, your changes should follow the same style.

2017-08-11 14:26 UTC, stephanemagnenat requested changes
Besides the specific issues I pointed out in the code, there is a general design problem with MarkeModel, as there should not be marker-specific code in the C++ part. Rather, there should be C++ classes and functions that are used in the QML code to encode the specific logic of marker fusion. Beside that, the indentation does not match the project one, so this should be corrected.

2017-08-11 14:26 UTC, stephanemagnenat commented on AdaHouse.qml
> +                source: "/models/bluehouse.qgltf"       // at the moment i use the 3d model of the blue house for the ada house
Why? I'm sure there is a good reason so it will be helpful to write it down.

2017-08-11 14:26 UTC, stephanemagnenat commented on BlueHouse.qml
> +                //rotation: fromAxisAndAngle(Qt.vector3d(0,0,1), 180) // -> necessary?
If the model works correctly without the transform, please remove it.

2017-08-11 14:26 UTC, stephanemagnenat commented on OrangeHouse.qml
> +    property matrix4x4 t
It would be more helpful to name the transform with its semantic meaning, for instance worldPose.

2017-08-11 14:26 UTC, stephanemagnenat commented on OrangeHouse.qml
> +                rotation: fromAxisAndAngle(Qt.vector3d(0,0,1), 180) // buggy 3d model?
Initially that was not necessary, so I am not sure the 3D model is buggy, maybe the world to camera transform has a problem?

2017-08-11 14:26 UTC, stephanemagnenat commented on android/AndroidManifest.xml
> +    <uses-sdk android:minSdkVersion="17" android:targetSdkVersion="23"/>
Why do we now need version 17 of the SDK?

2017-08-11 14:26 UTC, stephanemagnenat commented on main.qml
> +    // HACK
Why? If it is a hack, why is it still here? If it works around a bug in Qt, then please explain in detail why this is here.

2017-08-11 14:26 UTC, stephanemagnenat commented on main.qml
> +    // Timer to update model.
Update which model with which information?

2017-08-11 14:26 UTC, stephanemagnenat commented on main.qml
> +        Connections {
Please try to use a `Repeater` to avoid duplication.

2017-08-11 14:26 UTC, stephanemagnenat commented on markermodel.cpp
> +     * > The position of the marker relative to eachother is fix.
"eachother" => "each other"

2017-08-11 14:26 UTC, stephanemagnenat commented on markermodel.h
> +class MarkerModel : public QObject, public TransMem {
What is a marker model? There should be a minimum of documentation here.

2017-08-11 14:26 UTC, stephanemagnenat commented on markermodel.h
> +    // Private members (P for private)
Do not encode visibility of members into their names.

2017-08-11 14:26 UTC, stephanemagnenat commented on markermodel.h
> +                    const qPair &transf, const float &conf);
Do not pass const reference to basic types, just pass by copy.

2017-08-11 14:26 UTC, stephanemagnenat commented on markermodel.h
> +    virtual ~Analysis(){}
Do not write an empty destructor like this, just tell the compiler to use the default one: `virtual ~Analysis() = default;`.

2017-08-11 14:26 UTC, stephanemagnenat commented on markermodel.h
> +/* This analysis compares the for each link update, the transformation with the transformation
"This analysis compares the for [...]", the what?

2017-09-27 19:40 UTC, closed without merging